config/routes.rb
Rails.application.routes.draw do
  resources :movies, only: [:index, :new, :create]
  resources :series, only: [:index, :new, :create]
  resources :documentary_films, only: [:index, :new, :create]

  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/models/serie.rb
class Serie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documentary_films_controller.rb
class DocumentaryFilmsController < ApplicationController
  def index
    @documentary_films = DocumentaryFilm.all
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentary_film_params)
    if @documentary_film.save
      redirect_to documentary_films_path, notice: 'Documentary Film was successfully created.'
    else
      render :new
    end
  end

  private

  def documentary_film_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: 'Movie was successfully created.'
    else
      render :new
    end
  end

  private

  def movie_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Serie.all
  end

  def new
    @serie = Serie.new
  end

  def create
    @serie = Serie.new(serie_params)
    if @serie.save
      redirect_to series_path, notice: 'Serie was successfully created.'
    else
      render :new
    end
  end

  private

  def serie_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentary_films_helper.rb
module DocumentaryFilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentary_films/_form.html.erb
<%= form_with model: documentary_film, local: true, class: 'form' do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :synopsis, class: 'form-label' %>
    <%= form.text_area :synopsis, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :director, class: 'form-label' %>
    <%= form.text_field :director, class: 'form-control' %>
  </div>

  <%= form.submit 'Agregar un documental', class: 'btn btn-primary' %>
<% end %>

app/views/documentary_films/index.html.erb
<div class="container">
  <h1>Documentales</h1>
  
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Sinopsis</th>
        <th>Director</th>
      </tr>
    </thead>
    <tbody>
      <% @documentary_films.each do |documentary| %>
        <tr>
          <td><%= documentary.name %></td>
          <td><%= documentary.synopsis %></td>
          <td><%= documentary.director %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%= link_to 'Nuevo Documental', new_documentary_film_path, class: 'btn btn-primary' %>
</div>

app/views/documentary_films/new.html.erb
<div class="container">
<h1>New Documentary Film</h1>
<%= render 'form', documentary_film: @documentary_film %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>
<body>

<div class="navbar">
  <ul>
    <li><%= link_to 'Películas', movies_path %></li>
    <li><%= link_to 'Series', series_path %></li>
    <li><%= link_to 'Documentales', documentary_films_path %></li>
  </ul>
</div>

<div class="content">
  <%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_with model: movie, local: true, class: 'form' do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :synopsis, class: 'form-label' %>
    <%= form.text_area :synopsis, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :director, class: 'form-label' %>
    <%= form.text_field :director, class: 'form-control' %>
  </div>

  <%= form.submit 'Agregar una película', class: 'btn btn-primary' %>
<% end %>

app/views/movies/index.html.erb
<div class="container">
  <h1>Películas</h1>
  
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Sinopsis</th>
        <th>Director</th>
      </tr>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.name %></td>
          <td><%= movie.synopsis %></td>
          <td><%= movie.director %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%= link_to 'Nueva Película', new_movie_path, class: 'btn btn-primary' %>
</div>

app/views/movies/new.html.erb
<div class="container"><h1>New Movie</h1>
<%= render 'form', movie: @movie %>
</div>

app/views/series/_form.html.erb
<%= form_with model: serie, local: true, class: 'form' do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :synopsis, class: 'form-label' %>
    <%= form.text_area :synopsis, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :director, class: 'form-label' %>
    <%= form.text_field :director, class: 'form-control' %>
  </div>

  <%= form.submit 'Agregar una serie', class: 'btn btn-primary' %>
<% end %>

app/views/series/index.html.erb
<div class="container">
  <h1>Series</h1>
  
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Sinopsis</th>
        <th>Director</th>
      </tr>
    </thead>
    <tbody>
      <% @series.each do |serie| %>
        <tr>
          <td><%= serie.name %></td>
          <td><%= serie.synopsis %></td>
          <td><%= serie.director %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <%= link_to 'Nueva Serie', new_serie_path, class: 'btn btn-primary' %>
</div>

app/views/series/new.html.erb
<div class="container"><h1>New Serie</h1>
<%= render 'form', serie: @serie %>
</div>